apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
  namespace: test
spec:
  scaleTargetRef:
    name: rabbitmq-worker
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: rabbitmq
    metadata:
      queueName: task-queue
      host: "amqp://guest:guestpassword@rabbitmq.test.svc.cluster.local:5672/"
      protocol: amqp
      mode: QueueLength
      value: "5"  # Scale up if more than 5 messages in queue
